spring:
  application:
    name: backup-compressed

cloud-providers:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region: us-east-1
    s3:
      bucket: backup-compressed
